language: node_js
node_js: 10.16.0
script:
- yarn build
cache:
  directories:
  - .cache
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: public
  on:
    branch: master
