language: node_js
node_js: 10.16.0
script:
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: public
  on:
    branch: master
env:
  global:
  - secure: rycVsimo79BETvv8ZQ37yknfqYCjMxlfm9jgLQkrRorYkBgFMi1YvYvu3+MQb7VSl7KHGKoVMDoswtPYeceUG8nWo7A361+gGiIwHMl+tPhQb5anHjeTRgT7lFdScEthywL+hb8YWx0GaWsJltV2S4RsaLjpA375UCux1HJirH8zIwLfipL4kMj/a6MIF2MwI2fZp0k4dyC00r2lj7AeUysNdqyo9bujMDdAmjtA3jh2pOKBmC7iDVMeSTSzV6GkEUV2gPzaYYuT9E2zJVGPOxgnycqMI/s4jJrpMmC8RogmMO6XfUx5JuwGioV9fUQJBHcRwYQnnLu1UDo3bzK9TSxwc7BBddJS7F2rEINwiYiOrsHxbyWht892cMkFci/yL8IWOXVm21pW2FoZcsllYw0OZPBC1uVyMbncnlP0Ws5EZTVSKpPQ1KoQQw38Grtx27+Uos5pVUqYKN+eg1R2zY1Xgscqk4SM8CpqIM5iQrUlIX+ndv+bZXuo98UbcYBV+K5E0tsstW3EvfC46y6NQv8yAVJl24uGa9AlD3edSDnL2i9wf9PezTfLGQVU8eD8EnzsJGC/aB0yIy7qgqAAwkkIWzBLGYFlWsigY5QyTyB9sER89fwaLlpws2HubBchrbiyaiIR3kuWHdOHArlMFRU0rHU5gqpXpRTXnslqSiM=
