name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: |
            .cache
            public
          key: run-gatsby-cache-v1
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          GATSBY_MAPBOX_TOKEN: ${{ secrets.GATSBY_MAPBOX_TOKEN }}
          GATSBY_SOURCE_STRAVA_TOKEN: ${{ secrets.GATSBY_SOURCE_STRAVA_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
